[package]
name = "chara_card"
version = "0.4.1"
edition = "2024"

description = "A library to deal with character card formats and `.charx` in Rust."
keywords = ["character-card", "charx", "llm", "schema"]
repository = "https://github.com/Sharp0802/chara_card.git"
license = "Apache-2.0"

[dependencies]
infer = "0.19"
isolang = { version = "2.4", features = ["serde"] }
jiff = { version = "0.2", features = ["serde"] }
mime_guess = "2.0"
paste = "1.0"
serdev = { version = "0.3", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
url = { version = "2.5", features = ["serde"] }
urlencoding = "2.1"
winnow = "1.0"
zip = "8.6"

[dev-dependencies]
assert-json-diff = "2.0"
rstest = "0.26"
